name: Custom Deployment

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: autoCheckout
      uses: actions/checkout@v2

    - name: Set up Node.js
      id: autoNode
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      id: npmInstall
      run: npm install

    - name: Set credentials
      id: credentials
      run: |
        git config user.email ""
        git config user.name "$Custom Deployment"

    - name: Generate build
      id: build
      run: |
        git checkout deploy
        git status
        git checkout HEAD -- .
        git pull
        git status
        npm run build
        git status
        git add .
        git status
        git commit -m "$Generated Vite build"
        git status
        git push

    - name: Update main branch
      id: branchMerge
      run: |
        git checkout main
        git status
        git checkout HEAD -- .
        git pull origin deploy
      continue-on-error: true

    - name: Verify merge conflict
      id: verifyMerge
      run: |
        if git diff --name-only --diff-filter=U | grep -q .; then
          git status
          echo "CONFLICTS DETECTED! Please resolve conflicts by manually pulling 'main' into 'deploy' or any other way."
          exit 1
        fi

    - name: Push to main
      id: pushToMain
      run: |
        if [ ${{ steps.branchMerge.outcome }} == "success" ]; then
          git push
        fi