name: Custom Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run npm build
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        # Default GitHub Pages deployment task
        git config user.email ""
        git config user.name "$Custom Deployment"
        git fetch --prune --unshallow
        git checkout main
        git clean -ffdx
        git pull
        git checkout HEAD -- .
        git add -A
        git commit -m "$GitHub Pages deployment"
        git push